language: generic
addons:
  apt:
    packages:
      - sshpass
before_script:
  - echo -e "Host fomodeals.org\n\tStrictHostKeyChecking no\n\tUser fomodeals\n" >> ~/.ssh/config
script: sshpass -e ssh fomodeals.org fomodeals/deploy.sh
